CREATE TABLE `projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`rowNumber` int,
	`category` varchar(100),
	`projectName` text NOT NULL,
	`projectId` varchar(100),
	`ppdoCategory` varchar(100),
	`description` text,
	`location` text,
	`municipality` varchar(100),
	`implementingOffice` varchar(50),
	`fiscalYear` int,
	`sourceOfFund` varchar(200),
	`fundCategory` varchar(200),
	`projectCost` decimal(18,2),
	`contractCost` decimal(18,2),
	`calendarDays` int,
	`ntpDate` date,
	`extensionCount` int,
	`targetCompletionDate` date,
	`revisedCompletionDate` date,
	`dateCompleted` date,
	`progressPercent` decimal(5,2),
	`procurementMode` varchar(50),
	`status` varchar(100),
	`contractor` text,
	`contractorTin` varchar(50),
	`statusReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `projects_id` PRIMARY KEY(`id`)
);
