CREATE TABLE `annual_budgets` (
	`id` int AUTO_INCREMENT NOT NULL,
	`fiscalYear` int NOT NULL,
	`totalBudget` decimal(18,2) NOT NULL,
	`allocatedAmount` decimal(18,2) DEFAULT '0',
	`remainingAmount` decimal(18,2),
	`status` varchar(50) DEFAULT 'Draft',
	`approvedDate` date,
	`remarks` text,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `annual_budgets_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `biddings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`biddingNumber` varchar(50) NOT NULL,
	`powId` int,
	`projectTitle` text NOT NULL,
	`abc` decimal(18,2) NOT NULL,
	`procurementMode` varchar(100) DEFAULT 'Public Bidding',
	`status` varchar(50) DEFAULT 'Pre-Procurement',
	`preProcurementDate` date,
	`advertisementDate` date,
	`preBidDate` date,
	`bidSubmissionDeadline` timestamp,
	`bidOpeningDate` date,
	`bidEvaluationDate` date,
	`postQualificationDate` date,
	`bacResolutionDate` date,
	`noaDate` date,
	`contractSigningDate` date,
	`ntpDate` date,
	`winningBidder` text,
	`winningBidAmount` decimal(18,2),
	`contractCost` decimal(18,2),
	`numberOfBidders` int,
	`failedBiddingCount` int DEFAULT 0,
	`failedReason` text,
	`projectId` int,
	`remarks` text,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `biddings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `program_of_works` (
	`id` int AUTO_INCREMENT NOT NULL,
	`powNumber` varchar(50) NOT NULL,
	`projectTitle` text NOT NULL,
	`description` text,
	`location` text,
	`municipality` varchar(100),
	`category` varchar(100),
	`budgetId` int,
	`fiscalYear` int NOT NULL,
	`estimatedCost` decimal(18,2) NOT NULL,
	`sourceOfFund` varchar(200) DEFAULT '20% Development Fund',
	`status` varchar(50) DEFAULT 'Draft',
	`planningDivision` varchar(50) DEFAULT 'Planning',
	`dedStatus` varchar(50) DEFAULT 'Not Started',
	`dedCompletedDate` date,
	`plansSpecsReady` boolean DEFAULT false,
	`targetBiddingDate` date,
	`targetStartDate` date,
	`targetCompletionDate` date,
	`calendarDays` int,
	`projectId` int,
	`biddingId` int,
	`remarks` text,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `program_of_works_id` PRIMARY KEY(`id`)
);
