CREATE TABLE `contract_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contractorId` int NOT NULL,
	`projectId` int,
	`biddingId` int,
	`contractNumber` varchar(100),
	`projectTitle` text NOT NULL,
	`clientName` varchar(200) DEFAULT 'Province of Palawan - PEO',
	`contractAmount` decimal(18,2),
	`startDate` date,
	`originalCompletionDate` date,
	`actualCompletionDate` date,
	`status` varchar(50) DEFAULT 'Ongoing',
	`timeExtensions` int DEFAULT 0,
	`extensionDays` int DEFAULT 0,
	`variationOrders` int DEFAULT 0,
	`variationAmount` decimal(18,2) DEFAULT '0',
	`finalAmount` decimal(18,2),
	`performanceRating` decimal(3,2),
	`liquidatedDamages` decimal(18,2) DEFAULT '0',
	`remarks` text,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contract_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contractors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` text NOT NULL,
	`tradeName` text,
	`tin` varchar(50),
	`philgepsNumber` varchar(50),
	`pcabLicense` varchar(50),
	`pcabCategory` varchar(20),
	`pcabClassification` varchar(100),
	`licenseExpiryDate` date,
	`address` text,
	`city` varchar(100),
	`province` varchar(100),
	`contactPerson` varchar(200),
	`email` varchar(320),
	`phone` varchar(50),
	`mobile` varchar(50),
	`status` varchar(50) DEFAULT 'Active',
	`blacklistReason` text,
	`blacklistDate` date,
	`overallRating` decimal(3,2),
	`totalContracts` int DEFAULT 0,
	`totalContractValue` decimal(18,2) DEFAULT '0',
	`completedContracts` int DEFAULT 0,
	`ongoingContracts` int DEFAULT 0,
	`remarks` text,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contractors_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `performance_ratings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contractorId` int NOT NULL,
	`contractHistoryId` int,
	`projectId` int,
	`evaluationPeriod` varchar(50),
	`qualityRating` decimal(3,2),
	`timelinessRating` decimal(3,2),
	`safetyRating` decimal(3,2),
	`resourceRating` decimal(3,2),
	`communicationRating` decimal(3,2),
	`overallRating` decimal(3,2),
	`evaluatorName` varchar(200),
	`evaluatorPosition` varchar(100),
	`evaluationDate` date,
	`strengths` text,
	`areasForImprovement` text,
	`comments` text,
	`createdById` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `performance_ratings_id` PRIMARY KEY(`id`)
);
